package com.kvarela.marshaling_sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class MyObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "MYOBJECT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "MYOBJECT_ID_GENERATOR", sequenceName = "MYOBJECT_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String name;

	public MyObject() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public MyObject(java.lang.Long id, java.lang.String name) {
		this.id = id;
		this.name = name;
	}

}